### ISSUE TITLE
field_equals with array fails using search()/searchlogic()

### ISSUE THREAD

**Issue by zacheryph** [binarylogic/searchlogic#81] opened 2010-04-05 15:51 UTC
one of the examples, works as a stand alone scope but not when used in Model#searchlogic()

```
User.username_equals(["bjohnson", "thunt"])
```

This is locally on current app with code from commit (d6225e982aba)

```
>> Zone.type_equals('State').count
=> 50
>> Zone.type_equals(['State', 'Province']).count
=> 61
>> Zone.search({:type_equals => 'State'}).count
=> 50
>> Zone.search({:type_equals => ['State', 'Province']}).count
/Users/zacheryph/src/cserp/vendor/plugins/searchlogic/lib/searchlogic/named_scopes/conditions.rb:116: warning: multiple values for a block parameter (2 for 1)
```

However. using `field_equals_any` in searchlogic() does work.  Is there a reason there is a differentiation
between the two and they dont match eachother?

**Comment by graywh** [comment] 2010-05-14 16:45
They don't do the same thing.  Note that Model.field_is_any([]).count == Model.count.

**Comment by zacheryph** [comment] 2010-05-15 02:03
I was pointing Out That search() requires using a named_scope. These named Scopes made by search logic. The named scope directly and "the named scope" that search() is hitting do not match. Why would they differ?

**Comment by graywh** [comment] 2010-05-17 14:00
Also, this might be a duplicate of issue #64.

**Comment by graywh** [comment] 2010-05-17 14:04
And issue #57.

**Closed as completed** 2018-07-17 00:19 UTC
