### ISSUE TITLE
OR fails with associated classes

### ISSUE THREAD

**Issue by twalpole** [binarylogic/searchlogic#23] opened 2009-08-24 21:17 UTC
Using OR searches with associated classes fails with Searchlogic::NamedScopes::OrConditions::UnknownConditionError errors

**Comment by laserlemon** [comment] 2009-10-01 18:45
I also encountered this and just confirmed it as a bug. The README says that the OR-joined scopes should work with scopes on associations but that doesn't seem to be the case and the code comments make it seem as though it's still pending.

In my fork, I've written a failing test and a possible solution which passes the test.

http://github.com/laserlemon/searchlogic

**Comment by swards** [comment] 2010-01-23 17:39
I also encountered this.  The query created uses an inner join, where a left outer join would produce the desired results.  In my case, the associations are not required, so the query returns no results.

**Comment by konzeptual** [comment] 2010-02-04 12:57
This issue seams to be resolved in the very latest version ( I am using 2.4.7)

**Comment by twalpole** [comment] 2010-02-04 17:05
Yes - the issue I entered this for was fixed quite a few versions back

**Comment by twalpole** [comment] 2010-02-08 17:13
This can be closed

**Comment by cknoxrun** [comment] 2010-03-09 18:29
This issue seems to have reappeared in 2.4.11.  It is doing inner joins again when using ORs on associated scopes.  Can anyone else confirm this?

**Comment by mgomes** [comment] 2010-03-10 23:21
I am also experiencing this in 2.4.11

**Comment by cknoxrun** [comment] 2010-03-10 23:25
I ended up creating a custom named_scope for this case, and it seems to work.  I'm not sure if this is just how we were supposed to handle these joins all along?  I was still having this issue in 2.4.7, so maybe it is more a problem with the documentation?  Some clarifying thoughts from the authors/contributers would be helpful (thanks!).  Anyways, this is what I did, it might help for others:
    named_scope :names_like, lambda { |n| { :conditions => [ "drugs.name LIKE ? OR brands.name LIKE ? OR drug_synonyms.synonym LIKE ?", "%#{n}%", "%#{n}%", "%#{n}%" ], :joins => left_outer_joins([ :brands, :synonyms ]), :select => "DISTINCT drugs.*" } }

In my form I then have:
    <%= form.text_field :names_like, :title => 'Search name, brands, and synonyms' %>

**Comment by mgomes** [comment] 2010-03-11 00:24
I am trying to do something a little different. For example, say you have a parent model `Building` and it `has_many :rooms`.

If you attempt `Room.building_meets_code_or_building_energy_efficient(1)` Searchlogic will attempt to search for attributes in Building named `meets_code_` and `energy_efficient_`. Note the extra underscore.

To get around this behavior I created corresponding named_scopes that contain the extra underscore.

**Comment by noahduncan** [comment] 2011-02-03 23:59
@cknoxrun I have the same issue in 2.4.27, some detail on my setup follows
:part (has description and extended_description_id fields)
belongs_to :extended_description

:extended_description (has body field)
has_one :part

Calling:
Part.description_or_extended_description_body_like("heater")
yields an inner join of Part.description and ExtendedDescription.body

**Comment by nbarthelemy** [comment] 2011-04-07 17:23
I dealt with this issue in 2.4.27 and 2.5.4. The issue is line 108 in or_condition.rb. It need to be:

path << details[:association].name

not

path << details[:association]

**Comment by ghost** [comment] 2011-04-07 17:46
I just released a fix, 2.5.5 fixes this. Thanks!

**Closed as completed by ghost** 2011-04-07 17:46 UTC
